apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaup-api
  namespace: kube-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yaup-api
  template:
    metadata:
      labels:
        app: yaup-api
    spec:
      containers:
        - name: yaup-api
          image: oreze/yaup-api:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
