apiVersion: v1
kind: Service
metadata:
  name: yaup-api-service
  namespace: kube-system
spec:
  selector:
    app: yaup-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
